language: python
sudo: false
cache: false
python:
    - 3.5
env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy
    - TOXENV=pypy3
install:
    - travis_retry pip install tox
script: tox
