language: python
sudo: false
cache: false
python:
    - 3.5
env:
    - TOXENV=2.7
    - TOXENV=3.3
    - TOXENV=3.4
    - TOXENV=3.5
    - TOXENV=pypy
install:
    - travis_retry pip install tox
script: tox
